### PR TITLE
Allow autoparcel.vm resource instead of templateStr variable

### PR DESCRIPTION
**Pull request by yongjhih**

### CODE REVIEW

**Comment by frankiesardo** [comment]
Could you just move the `autoparcel.vm` under `resources` instead of adding the `src` folder in the `build.gradle` file?

**Comment by yongjhih** [comment]
I think the static `class.getResourceAsStream(resourceName)` is load the same path of resource, its easier way by set resources.dirs.

**Comment by yongjhih** [comment]
Here is another way by moving autoparcel.vm to corresponding resources path of `src/main/resources/auto/parcel/processor/autoparcel.vm`:

https://github.com/yongjhih/auto-parcel/tree/auto-parcel_vm2

What do you think?

**Comment by frankiesardo** [comment]
I'd rather not mix the concept of source code and static resources, so I'm happy to merge the second PR

**Comment by yongjhih** [comment]
It's not bad. I'll force-update this PR for regular structure.

**Pull request merged**
