### PR TITLE
hashCode fails with h property

### PR DESCRIPTION
**Pull request by cranberyxl**
`h` is effectively a reserved property because it's used in the generated hashCode method

`error: int cannot be dereferenced`

### CODE REVIEW

**Comment by frankiesardo** [comment]
I suggest you open the issue first on the [google/auto](https://github.com/google/auto) repo and then I'll merge it back here when it's accepted.

**Comment by cranberyxl** [comment]
Opened here for tracking: https://github.com/google/auto/pull/252

**Comment by cranberyxl** [comment]
The PR has been merged

**Comment by frankiesardo** [comment]
Well done. Can you please force push the same strategy you used for auto/value?

**Comment by cranberyxl** [comment]
Updated

**Comment by frankiesardo** [comment]
:+1:

**Pull request merged**
